### ISSUE TITLE
[for Blazemeter/taurus] Build tries to write into /usr/local instead of the stage dir.

### ISSUE THREAD

**Issue by yurivict** [Blazemeter/blazemeter-jenkins-plugin#9]
Sorry, but Blazemeter/taurus doesn't have the 'Issues' page.
---

Build fails:
```
Installing bzt script to /usr/ports/devel/py-taurus/work/stage/usr/local/bin
Installing jmx2yaml script to /usr/ports/devel/py-taurus/work/stage/usr/local/bin
Installing soapui2yaml script to /usr/ports/devel/py-taurus/work/stage/usr/local/bin
writing list of installed files to '/usr/ports/devel/py-taurus/work/.PLIST.pymodtmp'
[1.8.3] Creating /usr/local/etc/bzt.d
error: [Errno 13] Permission denied: '/usr/local/etc/bzt.d'
*** Error code 1
```

It attempts to install into the read-only directory while it is supposed to install into the stage directory. setup.py should install only into the provided stage directory.

setup.py is passed these arguments that it should use to determine the installation directory: --record /usr/ports/devel/py-ptrace/work/.PLIST.pymodtmp  -c -O1 --prefix=/usr/local --single-version-externally-managed --root=/usr/ports/devel/py-ptrace/work/stage

Found this while trying to create a FreeBSD port.

**Comment by dzmitrykashlach** [comment]
Please, post there:
https://groups.google.com/forum/#!forum/codename-taurus
